import {
  Apple,
  BriefcaseBusiness,
  BriefcaseMedical,
  CreditCard,
  Flower,
  Gift,
  GraduationCap,
  House,
  Landmark,
  Plane,
  Popcorn,
  Receipt,
  Shield,
  ShoppingBag,
  Star,
  TrainFront,
  Utensils,
  Volleyball,
  Wrench,
} from "lucide-react";

export const CATEGORY_ICONS: Record<string, React.ComponentType> = {
  "Bank Movements": CreditCard,
  Dining: Utensils,
  Education: GraduationCap,
  Entertainment: Popcorn,
  Fitness: Volleyball,
  "Gifts and Donations": Gift,
  "Government Benefits": Landmark,
  Groceries: Apple,
  Health: BriefcaseMedical,
  Housing: House,
  Insurance: Shield,
  "Other Income": Star,
  "Personal Care": Flower,
  "Primary Income": BriefcaseBusiness,
  Services: Wrench,
  Shopping: ShoppingBag,
  "Taxes and Fines": Receipt,
  Transportation: TrainFront,
  Travel: Plane,
};
